AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 165

Metrics/ModuleLength:
  Max: 165
  Exclude:
    - 'lib/skull_island/helpers/resource.rb'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 35
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Layout/IndentHeredoc:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/skull_island/cli.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*_spec.rb'
